name: CI

on:
  push:
    branches-ignore:
      - "wip*"
    tags:
      - "v*"
  pull_request:
  schedule:
    # Daily at 8:33
    - cron: "33 8 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  checks:
    name: Build, lint and unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-read-only: ${{ github.ref_name != 'main' }}
          cache-disabled: ${{ github.ref_type == 'tag' }} # zizmor: ignore[cache-poisoning]
      - name: Formatting, detekt, lint, unit tests, release build
        run: ./gradlew spotlessCheck detekt :app:lintDebug :app:testDebugUnitTest :app:assembleRelease

  instrumented:
    name: Instrumented tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-read-only: true
          cache-disabled: ${{ github.ref_type == 'tag' }} # zizmor: ignore[cache-poisoning]
      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
      - uses: reactivecircus/android-emulator-runner@a421e43855164a8197daf9d8d40fe71c6996bb0d # v2.38.0
        with:
          api-level: 37.1
          system-image-api-level: 37.1
          target: google_apis_ps16k
          arch: x86_64
          profile: pixel_6
          disable-animations: true
          script: ./gradlew :app:connectedDebugAndroidTest
